spring:
  datasource:
    url: ${DB_URL:jdbc:h2:file:./data/appdb}
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2
      enabled: true